packages:
  - "lib/*"
  - "dataset"
  - "ui"
  - "control/track-occupancy"
  - "control/dcc-ex-bridge"
  - "webthrottle"
allowBuilds:
  "@serialport/bindings-cpp": true
  esbuild: true
  onnxruntime-node: true
  protobufjs: true
  sharp: true
